# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidoP', models.CharField(max_length=50, verbose_name='Apellido Paterno')),
                ('apellidoM', models.CharField(max_length=50, verbose_name='Apellido Materno')),
                ('dni', models.CharField(max_length=50, verbose_name='DNI')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion')),
                ('celular', models.CharField(max_length=50, verbose_name='Celular')),
                ('ruc', models.CharField(max_length=50, verbose_name='RUC')),
            ],
            options={
                'verbose_name_plural': 'Personas',
                'verbose_name': 'Persona',
            },
        ),
    ]
