# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transBack', '0002_auto_20171025_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fechaIni', models.DateField(verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateField(verbose_name='Fecha Fin')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Costo')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transBack.Proovedor')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transBack.Unidad')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
            },
        ),
    ]
