# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transBack', '0002_auto_20171025_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('funcion', models.CharField(max_length=50, verbose_name='Funcion')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('personales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transBack.Personal')),
            ],
            options={
                'verbose_name': 'Personale',
                'verbose_name_plural': 'Personales',
            },
        ),
    ]
